do not test
Change-Id: I7287388927e5e6cf2f36f59834c655161b1241d2

diff --git a/.github/workflows/create-wheels.yaml b/.github/workflows/create-wheels.yaml
--- a/.github/workflows/create-wheels.yaml
+++ b/.github/workflows/create-wheels.yaml
@@ -58,22 +58,22 @@ jobs:
         run: |
           pip wheel -w dist --no-use-pep517 -v .
 
-      - name: Install wheel
-        run: |
-          pip install -f dist --no-index sqlalchemy
+      # - name: Install wheel
+      #   run: |
+      #     pip install -f dist --no-index sqlalchemy
 
-      - name: Check c extensions
-        # on windows in python 2.7 and 3.5 the cextension fail to build.
-        # for python 2.7 visual studio 9 is missing
-        # for python 3.5 the linker has an error "cannot run 'rc.exe'"
-        if: matrix.os != 'windows-latest' || ( matrix.python-version != '2.7' && matrix.python-version != '3.5' )
-        run: |
-          python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'
+      # - name: Check c extensions
+      #   # on windows in python 2.7 and 3.5 the cextension fail to build.
+      #   # for python 2.7 visual studio 9 is missing
+      #   # for python 3.5 the linker has an error "cannot run 'rc.exe'"
+      #   if: matrix.os != 'windows-latest' || ( matrix.python-version != '2.7' && matrix.python-version != '3.5' )
+      #   run: |
+      #     python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'
 
-      - name: Test created wheel
-        run: |
-          pip install pytest pytest-xdist ${{ matrix.extra-requires }}
-          pytest -n2 -q test -k 'not MockReconnectTest' --nomemory
+      # - name: Test created wheel
+      #   run: |
+      #     pip install pytest pytest-xdist ${{ matrix.extra-requires }}
+      #     pytest -n2 -q test -k 'not MockReconnectTest' --nomemory
 
       - name: Upload wheel
         uses: actions/upload-artifact@v1
