complete?
Change-Id: If88757ccd42f5cb0ae16cb98502498ecfd7bcf2f

diff --git a/.github/workflows/create-wheels.yaml b/.github/workflows/create-wheels.yaml
--- a/.github/workflows/create-wheels.yaml
+++ b/.github/workflows/create-wheels.yaml
@@ -6,9 +6,11 @@ on:
 
 env:
   PYTHONNOUSERSITE: 1
+  # comment TWINE_REPOSITORY_URL to use the real pypi
+  TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
 
 jobs:
-  # two jobs are defined make-wheel-win-osx and make-wheel-linux.
+  # Two jobs are defined make-wheel-win-osx and make-wheel-linux.
   # They do the the same steps, but linux wheels need to be build to target manylinux
   make-wheel-win-osx:
     name: ${{ matrix.python-version }}-${{ matrix.architecture }}-${{ matrix.os }}
@@ -17,12 +19,12 @@ jobs:
       matrix:
         os:
           - 'windows-latest'
-          # - 'macos-latest'
+          - 'macos-latest'
         python-version:
           - '2.7'
-          # - '3.5'
-          # - '3.6'
-          # - '3.7'
+          - '3.5'
+          - '3.6'
+          - '3.7'
           - '3.8'
         architecture:
           - x64
@@ -33,8 +35,6 @@ jobs:
             extra-requires: 'mock'
 
         exclude:
-          - os: 'ubuntu-latest'
-            architecture: x86
           - os: 'macos-latest'
             architecture: x86
 
@@ -56,22 +56,22 @@ jobs:
           pip install setuptools wheel
           pip wheel -w dist --no-use-pep517 -v .
 
-      # - name: Install wheel
-      #   run: |
-      #     pip install -f dist --no-index sqlalchemy
+      - name: Install wheel
+        run: |
+          pip install -f dist --no-index SQLAlchemy-test-caselit
 
-      # - name: Check c extensions
-      #   # on windows in python 2.7 and 3.5 the cextension fail to build.
-      #   # for python 2.7 visual studio 9 is missing
-      #   # for python 3.5 the linker has an error "cannot run 'rc.exe'"
-      #   if: matrix.os != 'windows-latest' || ( matrix.python-version != '2.7' && matrix.python-version != '3.5' )
-      #   run: |
-      #     python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'
+      - name: Check c extensions
+        # on windows in python 2.7 and 3.5 the cextension fail to build.
+        # for python 2.7 visual studio 9 is missing
+        # for python 3.5 the linker has an error "cannot run 'rc.exe'"
+        if: matrix.os != 'windows-latest' || ( matrix.python-version != '2.7' && matrix.python-version != '3.5' )
+        run: |
+          python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'
 
-      # - name: Test created wheel
-      #   run: |
-      #     pip install pytest pytest-xdist ${{ matrix.extra-requires }}
-      #     pytest -n2 -q test -k 'not MockReconnectTest' --nomemory
+      - name: Test created wheel
+        run: |
+          pip install pytest pytest-xdist ${{ matrix.extra-requires }}
+          pytest -n2 -q test -k 'not MockReconnectTest' --nomemory
 
       - name: Get wheel name
         id: wheel-name
@@ -92,7 +92,7 @@ jobs:
 
       - name: Set up Python for twine
         # twine on py2 is very old.
-        # the action 
+        # the action https://github.com/marketplace/actions/python-wheels-manylinux-build runs only on linux
         uses: actions/setup-python@v1
         with:
           python-version: '3.8'
@@ -102,8 +102,6 @@ jobs:
           TWINE_USERNAME: __token__
           # replace TWINE_PASSWORD with token for real pypi
           TWINE_PASSWORD: ${{ secrets.test_pypi_token }}
-          # comment TWINE_REPOSITORY_URL to use the real pypi
-          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
         run: |
           pip install -U twine
           twine upload --skip-existing dist/*
@@ -117,9 +115,9 @@ jobs:
           - 'ubuntu-latest'
         python-version:
           - '2.7'
-          # - '3.5'
-          # - '3.6'
-          # - '3.7'
+          - '3.5'
+          - '3.6'
+          - '3.7'
           - '3.8'
         architecture:
           - x64
@@ -159,22 +157,18 @@ jobs:
           build-requirements: 'setuptools wheel'
           pip-wheel-args: '--no-use-pep517 -v --no-deps'
 
-      # - name: Install wheel
-      #   run: |
-      #     pip install -f wheelhouse --no-index sqlalchemy
+      - name: Install wheel
+        run: |
+          pip install -f wheelhouse --no-index SQLAlchemy-test-caselit
 
-      # - name: Check c extensions
-      #   # on windows in python 2.7 and 3.5 the cextension fail to build.
-      #   # for python 2.7 visual studio 9 is missing
-      #   # for python 3.5 the linker has an error "cannot run 'rc.exe'"
-      #   if: matrix.os != 'windows-latest' || ( matrix.python-version != '2.7' && matrix.python-version != '3.5' )
-      #   run: |
-      #     python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'
+      - name: Check c extensions
+        run: |
+          python -c 'from sqlalchemy import cprocessors, cresultproxy, cutils'
 
-      # - name: Test created wheel
-      #   run: |
-      #     pip install pytest pytest-xdist ${{ matrix.extra-requires }}
-      #     pytest -n2 -q test -k 'not MockReconnectTest' --nomemory
+      - name: Test created wheel
+        run: |
+          pip install pytest pytest-xdist ${{ matrix.extra-requires }}
+          pytest -n2 -q test -k 'not MockReconnectTest' --nomemory
 
       - name: Get wheel names
         id: wheel-name
@@ -207,7 +201,7 @@ jobs:
 
       - name: Set up Python for twine
         # twine on py2 is very old.
-        # the action 
+        # the action https://github.com/marketplace/actions/python-wheels-manylinux-build runs only on linux
         uses: actions/setup-python@v1
         with:
           python-version: '3.8'
@@ -217,8 +211,6 @@ jobs:
           TWINE_USERNAME: __token__
           # replace TWINE_PASSWORD with token for real pypi
           TWINE_PASSWORD: ${{ secrets.test_pypi_token }}
-          # comment TWINE_REPOSITORY_URL to use the real pypi
-          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
         run: |
           pip install -U twine
           twine upload --skip-existing wheelhouse/*manylinux*
